version: '3'
services:

  ### Mariadb Container #######################################
  mariadb:
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    container_name: mariadb
    # restart: always
    networks:
      - backend

### Network ###############################################
networks:
  backend:
    driver: "bridge"
